window.ANG_HR_CONFIG = {
  edition: 'plus',
  editionName: 'ANG HR Plus',
  apiBaseUrl: 'https://script.google.com/macros/s/AKfycbzSwufSpMlK-DdmrxJ6m-jZvUT__iSUsDdCNXQaXUbCScs_-h9MTWP_7grMIq03RzILbQ/exec',
  defaultPage: 'admin',
  features: {
    employeeLogin: true,
    employeeHome: true,
    todayStatus: true,
    clockIn: true,
    clockOut: true,
    clockRecords: true,
    leave: true,
    clockFix: true,
    preselect: true,
    upload: true,
    notices: true,
    themeSave: true,
    adminHome: true,
    leaveReview: true,
    clockFixReview: true,
    uploadReview: true,
    messageReview: true,
    noticePublish: true,
    preselectSummary: true,
    scheduleCreate: true,
    schedulePublish: true,
    employeeScheduleCalendar: true,
    salaryDraft: true,
    shiftView: true,
    creatorPermissionCenter: false,
    officialSalary: false,
    laborInsurance: false,
    healthInsurance: false,
    pension: false,
    archive: false,
    driveExport: false,
    advancedSystemSettings: false
  }
};
